"""add_is_default_to_categories

Revision ID: 04fbc4c9398f
Revises: d9ac08efea96
Create Date: 2026-02-20 23:14:52.994755

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04fbc4c9398f'
down_revision: Union[str, None] = 'd9ac08efea96'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('is_default', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('categories', 'is_default')
    # ### end Alembic commands ###
