"""add_is_favorite_to_transactions

Revision ID: 8570786b7481
Revises: a3e7f2b1d5c8
Create Date: 2026-02-21 02:59:35.212307

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8570786b7481'
down_revision: Union[str, None] = 'a3e7f2b1d5c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('is_favorite', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'is_favorite')
    # ### end Alembic commands ###
