"""add_payment_method

Revision ID: 91fc1a350c9d
Revises: 04fbc4c9398f
Create Date: 2026-02-21 01:02:00.772898

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '91fc1a350c9d'
down_revision: Union[str, None] = '04fbc4c9398f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_cards',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('transactions', sa.Column('payment_type', sa.String(length=20), nullable=True))
    op.add_column('transactions', sa.Column('user_card_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'transactions', 'user_cards', ['user_card_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_column('transactions', 'user_card_id')
    op.drop_column('transactions', 'payment_type')
    op.drop_table('user_cards')
    # ### end Alembic commands ###
